### PR TITLE
chore(setup): test file changes github workflow I

### PR DESCRIPTION
**Pull request by erwin-leonardy-gojek**
Test Github File Changes workflow.

### CODE REVIEW

**Review by erwinleonardy — APPROVED** [review]
LGTM! But you still can't merge the PR unless you remove your style changes ;)

**Comment by erwin-leonardy-gojek** [comment]
Re-trigger NEW format checker workflow

**Comment by erwin-leonardy-gojek** [comment]
Re-trigger NEW format checker workflow II

**Comment by erwin-leonardy-gojek** [comment]
Re-trigger NEW format checker workflow II

**Comment by erwin-leonardy-gojek** [comment]
Re-trigger NEW format checker workflow IV

**Comment by erwin-leonardy-gojek** [comment]
Test Add Reviewer I

**Comment by erwin-leonardy-gojek** [comment]
Test Add Reviewer II

**Comment by erwin-leonardy-gojek** [comment]
Test add label and remove

**Comment by erwin-leonardy-gojek** [comment]
Test labels

**Comment by erwin-leonardy-gojek** [comment]
Closing this PR for good :)

**Pull request closed without merging**
